### ISSUE TITLE
Its broken please fix it

### ISSUE THREAD

**Issue by Intention1x** [AltimorTASDK/ClientSettingsEditor#17]
ITS BROKEN AND I CANT PLAY KOVAAKS :((

**Comment by Rikuro-30** [comment]
Intention1x Yes it has been down for like 3 or 4 weeks it seems. I'm sure AltimorTASDK is aware. He is either trying to work on it. Or he just hasn't been back on since it last work. You have to realize the people that makes these programs have a life, job, and a family. Please wait patiently like everyone else. Just use the fortnite slider setting in Kovaaks. It isnt spot on to your setting in Fortnite. But it is better then not playing kovaaks at all. Try playing on some of the fortnite creative kovaaks maps. That should help you till AltimorTASDK comes back to fix the program.

**Comment by AltimorTASDK** [comment]
Fixed
