### ISSUE TITLE
happy thanksgiving, please fix soon

### ISSUE THREAD

**Issue by Intention1x** [AltimorTASDK/ClientSettingsEditor#36]

**Comment by JustAHelper** [comment]
Ok you seem to be very impatient. What I’d suggest is that you try to find a recent clientsettings file from someone; either from someone who hasn’t played since the update, or one that saved it before the update.

Why should you do that? Well you can still upload <11.20 files to Epic as they will just transform it into the new one the next time you make a change within the game. This allows you to set your sensitivity to the value you like and use that for whatever you desire.

You may need to redo your bindings, but it is probably quicker and more productive than what you are doing now.

**Comment by zw5** [comment]
Dude like stop the fucking spam on issues that's gonna make him never update him
