### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by JustAHelper** [AltimorTASDK/ClientSettingsEditor#71]
Hi @AltimorTASDK,

I just wanted to check if you have stopped trying to make this project work, since the last we heard of you was over 2 months ago.

Unlike most others I used your app not for sensitivity for my mouse, but setting controller binds not possible within the game. After being on a trip for a couple of weeks, I just tried to upload my config that worked before I left,  to the game through your app, but even the login page doesn't seem to work anymore.

My hope is that you will still be able to make it work, or if you have decided it is not worth your time, maybe can provide some insights if it is actually still possible to make it work or not and if so where to start.

Regarding the login page not working anymore, has Epic removed this possibility or just change the link for example?

Hope you'll respond.

**Comment by AltimorTASDK** [comment]
I probably won't be releasing any more updates. I haven't played Fortnite since season 7.

It should still be possible to make it work. The login page is a web embed. Try running Fiddler while logging into the Epic launcher to see if the page was moved. It might also be necessary to update the Javascript callbacks that are provided to the login page.

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
